apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "fastapi-app.fullname" .) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "fastapi-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
